import { Component, OnInit } from '@angular/core';
import { A, O, P, S, U, Card } from 'src/dto/carddto';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

export class AppComponent implements OnInit {

  categories: string[][] = [['P', 'yellow'], ['O', 'navy'], ['A', 'grey'], ['?', 'green'], ['S', 'red']];

  nCard: number | undefined;
  card: Card | undefined;
  cat: string = "";

  data: any[] =  [{"cat": "P", "num": 1, "par": "DISCARICA"}, {"cat": "O", "num": 1, "par": "TOGA"}, {"cat": "A", "num": 0, "par": "SOLCARE"}, {"cat": "?", "num": 0, "par": "PORTA ASCIUGAMANO"}, {"cat": "S", "num": 0, "par": "AURORA BOREALE"}, {"cat": "P", "num": 1, "par": "CAMPANILE"}, {"cat": "O", "num": 0, "par": "CARBONE"}, {"cat": "A", "num": 0, "par": "CICATRIZZARSI"}, {"cat": "?", "num": 1, "par": "LETTORE DEL PENSIERO"}, {"cat": "S", "num": 0, "par": "MORSO DI SERPENTE"}, {"cat": "P", "num": 1, "par": "DISCOTECA"}, {"cat": "O", "num": 0, "par": "MOCASSINO"}, {"cat": "A", "num": 1, "par": "SOLLEVARE"}, {"cat": "?", "num": 0, "par": "GAS ESILARANTE"}, {"cat": "S", "num": 0, "par": "TERZO"}, {"cat": "P", "num": 0, "par": "COCCODRILLO"}, {"cat": "O", "num": 1, "par": "DOPOSCI"}, {"cat": "A", "num": 0, "par": "SGOBBARE"}, {"cat": "?", "num": 1, "par": "ALVEARE"}, {"cat": "S", "num": 0, "par": "PROIETTORE"}, {"cat": "P", "num": 1, "par": "OSPEDALE"}, {"cat": "O", "num": 1, "par": "PERLA"}, {"cat": "A", "num": 0, "par": "TRAFORARE"}, {"cat": "?", "num": 0, "par": "SCENARIO"}, {"cat": "S", "num": 0, "par": "ACUTO"}, {"cat": "P", "num": 0, "par": "PESCE VOLANTE"}, {"cat": "O", "num": 1, "par": "GHIRLANDA"}, {"cat": "A", "num": 1, "par": "SFREGARE"}, {"cat": "?", "num": 
  0, "par": "FREDDO"}, {"cat": "S", "num": 0, "par": "IMBUTO"}, {"cat": "P", "num": 1, "par": "PITTORE"}, {"cat": "O", "num": 0, "par": "MEGAFONO"}, {"cat": "A", "num": 0, "par": "OLIARE"}, {"cat": "?", "num": 1, "par": "GELOSO"}, {"cat": "S", "num": 0, "par": "CUSCINO"}, {"cat": "P", "num": 0, "par": "LAS VEGAS"}, {"cat": "O", "num": 0, "par": "PALO DEL TELEGRAFO"}, {"cat": "A", "num": 1, "par": "PUBBLICARE"}, {"cat": "?", "num": 1, "par": "GIOVANE"}, {"cat": "S", "num": 0, "par": "TERREMOTO"}, {"cat": "P", "num": 1, "par": "SERPENTE"}, {"cat": "O", "num": 0, "par": "FINESTRA"}, {"cat": "A", "num": 0, "par": "CONTROLLARE"}, {"cat": "?", "num": 1, "par": "CAROSELLO"}, {"cat": "S", "num": 0, "par": "INUTILE"}, {"cat": "P", "num": 1, "par": "DOLOMITI"}, {"cat": "O", "num": 0, "par": "SCIALUPPA DI SALVATAGGIO"}, {"cat": "A", "num": 0, "par": "CHIACCHIERARE"}, {"cat": "?", "num": 1, "par": "PREFISSO INTERNAZIONALE"}, {"cat": "S", "num": 0, "par": "UNGHIA"}, {"cat": "P", "num": 1, "par": "ANTARTICO"}, {"cat": "O", "num": 1, "par": "GRONDAIA"}, {"cat": "A", "num": 0, "par": "GRIDARE"}, {"cat": "?", "num": 0, "par": "FISICO"}, {"cat": "S", "num": 0, "par": "MASCHERA DELL'OSSIGENO"}, {"cat": "P", "num": null, "par": "GATTO SIAMESE"}, {"cat": "O", "num": 1, "par": "ARANCIO"}, {"cat": "A", "num": 1, "par": "SCOPPIARE"}, {"cat": "?", "num": null, "par": "ORIENTALE"}, {"cat": "S", "num": null, "par": "PREZZEMOLO"}, {"cat": "P", "num": null, "par": "MANTIDE RELIGIOSA"}, {"cat": "O", "num": null, "par": "CALCOLATRICE"}, {"cat": "A", "num": 1, "par": "AFFIGGERE"}, {"cat": "?", "num": 1, "par": "SCATTO"}, {"cat": "S", "num": null, "par": "DOVE"}, {"cat": "P", "num": 1, "par": "CANINO"}, {"cat": "O", "num": null, "par": "GAROFANO"}, {"cat": "A", "num": 1, "par": "DECOLLARE"}, {"cat": "?", "num": null, "par": "STENDARDO"}, {"cat": "S", "num": null, "par": "CURVA"}, {"cat": "P", "num": 1, "par": 
  "SPACCANAPOLI"}, {"cat": "O", "num": null, "par": "VESTITI"}, {"cat": "A", "num": null, "par": "ONDEGGIARE"}, {"cat": "?", "num": 1, "par": "CRESTA"}, {"cat": 
  "S", "num": null, "par": "INTIMO"}, {"cat": "P", "num": null, "par": "ALA"}, {"cat": "O", "num": null, "par": "FREEZER"}, {"cat": "A", "num": 1, "par": "LAVARE IL CERVELLO"}, {"cat": "?", "num": 1, "par": "FOGLIA DI FICO"}, {"cat": "S", "num": null, "par": "BIANCO"}, {"cat": "P", "num": 1, "par": "CONSERVATORE"}, {"cat": "O", "num": null, "par": "CIBO"}, {"cat": "A", "num": 1, "par": "PARTECIPARE"}, {"cat": "?", "num": null, "par": "CORSA A OSTACOLI"}, {"cat": "S", "num": 
  null, "par": "COSMONAUTA"}, {"cat": "P", "num": 1, "par": "FARAONE"}, {"cat": "O", "num": null, "par": "TAGLIATELLE"}, {"cat": "A", "num": 1, "par": "RUSSARE"}, {"cat": "?", "num": null, "par": "VEGLIARE"}, {"cat": "S", "num": null, "par": "GARA DI SCI"}, {"cat": "P", "num": 1, "par": "ATTORE"}, {"cat": "O", "num": 0, "par": "ARACHIDE"}, {"cat": "A", "num": 0, "par": "ANNEGARE"}, {"cat": "?", "num": 1, "par": "MATTO"}, {"cat": "S", "num": 0, "par": "CAOS"}, {"cat": "P", "num": 1, "par": "MURATORE"}, {"cat": "O", "num": null, "par": "SEDIA RECLINABILE"}, {"cat": "A", "num": null, "par": "SECCARE"}, {"cat": "?", "num": 1, "par": "MILIARDO"}, {"cat": "S", "num": null, "par": "LACCA"}, {"cat": "P", "num": 1, "par": "FORTE ALAMO"}, {"cat": "O", "num": null, "par": "FRITTATA"}, {"cat": "A", "num": 1, "par": "VESTIRSI"}, {"cat": "?", "num": null, "par": "STORIA"}, {"cat": "S", "num": null, "par": "VENERE DI MILO"}, {"cat": "P", "num": 1, "par": "MAIALE"}, {"cat": "O", "num": null, "par": "PUGNO DI FERRO"}, {"cat": "A", "num": null, "par": "VINCERE"}, {"cat": "?", "num": 1, "par": "SQUASH"}, {"cat": "S", "num": null, "par": "MEDICINA"}, {"cat": "P", "num": 1, "par": "ZANNA"}, {"cat": "O", "num": null, "par": "CALZONI ALLA ZUAVA"}, {"cat": "A", "num": null, "par": "SUPPORTARE"}, {"cat": "?", "num": 1, "par": "POMODORO"}, {"cat": "S", "num": null, "par": "CHIARO DI LUNA"}, {"cat": "P", "num": null, "par": "GALASSIA"}, {"cat": "O", "num": 1, "par": "MATERASSO"}, {"cat": "A", "num": null, "par": "LUCIDARE"}, {"cat": "?", "num": 1, "par": "NATALE"}, {"cat": "S", "num": null, "par": "NOTTE"}, {"cat": "P", "num": 1, "par": "SOGLIOLA"}, {"cat": "O", "num": null, "par": "BICICLETTA"}, {"cat": "A", "num": null, "par": "FERMENTARE"}, {"cat": "?", "num": 1, "par": "LIMITE DI VELOCITA'"}, {"cat": "S", "num": null, "par": "PROFONDO"}, {"cat": "P", "num": 1, "par": "AMERICA"}, {"cat": "O", "num": null, "par": "TAPPETO"}, {"cat": "A", "num": 1, "par": "GENERARE"}, {"cat": "?", "num": null, "par": "RALLENTATORE"}, {"cat": "S", "num": null, "par": "MAMMELLATA"}, {"cat": "P", "num": null, "par": "RIFUGIO ANTIAEREO"}, {"cat": "O", "num": 1, "par": "ELICOTTERO"}, {"cat": "A", "num": 1, "par": "TENTENNARE"}, {"cat": 
  "?", "num": null, "par": "RABBIA"}, {"cat": "S", "num": null, "par": "AUTOSTRADA"}, {"cat": "P", "num": null, "par": "AMERICA DEL NORD"}, {"cat": "O", "num": null, "par": "PICCHE"}, {"cat": "A", "num": 1, "par": "PROIBIRE"}, {"cat": "?", "num": 1, "par": "NERVO"}, {"cat": "S", "num": null, "par": "RANNUVOLARSI"}, {"cat": "P", "num": null, "par": "PALERMO"}, {"cat": "O", "num": 1, "par": "POP CORN"}, {"cat": "A", "num": null, "par": "POMPARE"}, {"cat": "?", "num": 1, "par": "ATTACCARE BOTTONE"}, {"cat": "S", "num": null, "par": "TAPPO DI SUGHERO"}, {"cat": "P", "num": null, "par": "PORTAMAZZE"}, {"cat": "O", "num": 1, "par": "TRAMPOLI"}, {"cat": "A", "num": null, "par": "CONTARE"}, {"cat": "?", "num": 1, "par": "CAPITALE"}, {"cat": "S", "num": null, "par": "CAVO ORALE"}, {"cat": "P", "num": null, "par": "DISCENDENTE"}, {"cat": "O", "num": 1, "par": "CANNA FUMARIA"}, {"cat": "A", "num": null, "par": "IMBALLARE"}, {"cat": "?", "num": 1, "par": "NUOVO"}, {"cat": "S", "num": null, "par": "MASCARA"}, {"cat": "P", "num": 1, "par": "CIMITERO"}, {"cat": "O", "num": null, "par": "JET"}, {"cat": "A", "num": 1, "par": "LAVARSI I CAPELLI"}, {"cat": "?", "num": null, "par": "PIGRO"}, {"cat": "S", "num": null, "par": "FANGO"}, {"cat": "P", "num": null, "par": "STREGONE"}, {"cat": "O", "num": 1, "par": "BOA"}, {"cat": "A", "num": 1, "par": "AVVOLGERE"}, {"cat": "?", "num": null, "par": "CAPELLI RICCI"}, {"cat": "S", "num": 
  null, "par": "\nSCRITTURA BRAILLE"}, {"cat": "P", "num": null, "par": "BLOCK NOTES"}, {"cat": "O", "num": 1, "par": "STRIMPELLARE"}, {"cat": "A", "num": 1, "par": "POLIESTERE"}, {"cat": "?", "num": null, "par": "SGABELLO DA BAR"}, {"cat": "S", "num": null, "par": 0}, {"cat": "P", "num": null, "par": "SEMINTERRATO"}, 
  {"cat": "O", "num": 1, "par": "ALBERO DELLA NAVE"}, {"cat": "A", "num": 1, "par": "INGRANDIRE"}, {"cat": "?", "num": null, "par": "SCAFFALATURA"}, {"cat": "S", "num": null, "par": "ORECCHINO"}, {"cat": "P", "num": null, "par": "POSTINO"}, {"cat": "O", "num": 1, "par": "TROMBONE"}, {"cat": "A", "num": 1, "par": "CUCIRE"}, {"cat": "?", "num": null, "par": "COSTATA"}, {"cat": "S", "num": null, "par": "TUFFO DI TESTA"}, {"cat": "P", "num": 0, "par": "TAVOLIERE DELLE PUGLIE"}, 
  {"cat": "O", "num": 1, "par": "COLLARE"}, {"cat": "A", "num": 0, "par": "CORRODERE"}, {"cat": "?", "num": 1, "par": "FORBICINA"}, {"cat": "S", "num": 0, "par": "PETROLIO"}, {"cat": "P", "num": 1, "par": "PETTIROSSO"}, {"cat": "O", "num": 1, "par": "ZAMPIRONE"}, {"cat": "A", "num": null, "par": "CANDEGGIARE"}, {"cat": "?", "num": null, "par": "COLON"}, {"cat": "S", "num": null, "par": "STRISCIA"}, {"cat": "P", "num": 1, "par": "INGRESSO"}, {"cat": "O", "num": null, "par": "CACCIAVITE"}, {"cat": "A", "num": null, "par": "PESCARE"}, {"cat": "?", "num": 1, "par": "SONNELLINO"}, {"cat": "S", "num": null, "par": "VULCANO"}, {"cat": "P", "num": 1, "par": "MUCCA"}, {"cat": "O", "num": null, "par": "MANUBRIO"}, {"cat": "A", "num": 1, "par": "VENDICARE"}, {"cat": "?", "num": null, "par": "PNEUMATICO RADIALE"}, {"cat": "S", "num": null, "par": "LUCE DI CANDELA"}, {"cat": "P", "num": 1, "par": "OSTRICA"}, {"cat": "O", "num": 1, "par": "CAVALLO DA CORSA"}, {"cat": "A", "num": null, "par": "SCHIZZARE"}, {"cat": "?", "num": null, "par": "VITA"}, {"cat": "S", "num": null, "par": "FILTRO PER OBIETTIVO"}, {"cat": 
  "P", "num": null, "par": "BOYSCOUT"}, {"cat": "O", "num": 1, "par": "MANICHINO"}, {"cat": "A", "num": null, "par": "DOMARE"}, {"cat": "?", "num": 1, "par": "LUNEDI'"}, {"cat": "S", "num": null, "par": "SECONDA MANO"}, {"cat": "P", "num": null, "par": "SAINT TROPEZ"}, {"cat": "O", "num": 1, "par": "PASTICCIO"}, {"cat": "A", "num": 1, "par": "CALCIARE"}, {"cat": "?", "num": null, "par": "PIEDI PIATTI"}, {"cat": "S", "num": null, "par": "DESIGNER"}, {"cat": "P", "num": 1, "par": "PALUDE"}, {"cat": "O", "num": null, "par": "INCROCIO"}, {"cat": "A", "num": null, "par": "VERIFICARE"}, {"cat": "?", "num": 1, "par": "RIPIANO"}, {"cat": 
  "S", "num": null, "par": "TRONCO"}, {"cat": "P", "num": null, "par": "DONNA BAFFUTA"}, {"cat": "O", "num": null, "par": "PIANOFORTE"}, {"cat": "A", "num": 1, "par": "INZUPPARE"}, {"cat": "?", "num": 1, "par": "LINEA LATERALE"}, {"cat": "S", "num": null, "par": "SMOG"}, {"cat": "P", "num": null, "par": "COTTAGE"}, {"cat": "O", "num": null, "par": "PRUGNA"}, {"cat": "A", "num": 1, "par": "STRILLARE"}, {"cat": "?", "num": 1, "par": "PRINCIPALE"}, {"cat": "S", "num": null, "par": "VALLETTA"}, {"cat": "P", "num": 1, "par": "ISRAELE"}, {"cat": "O", "num": null, "par": "ANGURIA"}, {"cat": "A", "num": null, "par": "CALCOLARE"}, {"cat": 
  "?", "num": 1, "par": "SPETTRO"}, {"cat": "S", "num": null, "par": "MENTE"}, {"cat": "P", "num": null, "par": "MUSCOLO"}, {"cat": "O", "num": 1, "par": "VESTIARIO"}, {"cat": "A", "num": 1, "par": "IMPASTARE"}, {"cat": "?", "num": null, "par": "PASSEGGIATA NELLO SPAZIO"}, {"cat": "S", "num": null, "par": "ILLUSIONE"}, {"cat": "P", "num": null, "par": "TARTARUGA"}, {"cat": "O", "num": 1, "par": "GRANATA"}, {"cat": "A", "num": null, "par": "SCORRERE"}, {"cat": "?", "num": 1, 
  "par": "RUGGINE"}, {"cat": "S", "num": null, "par": "SPILLA DA BALIA"}, {"cat": "P", "num": 1, "par": "PUMA"}, {"cat": "O", "num": 1, "par": "ALBERO DI NATALE"}, {"cat": "A", "num": null, "par": "FARE LA MANICURE"}, {"cat": "?", "num": null, "par": "PLOTONE D'ESECUZIONE"}, {"cat": "S", "num": null, "par": "CONTAGIOSO"}, {"cat": "P", "num": null, "par": "CASCATE DEL NIAGARA"}, {"cat": "O", "num": 1, "par": "PORTAFOGLIO"}, {"cat": "A", "num": 1, "par": "CUOCERE"}, {"cat": "?", "num": null, "par": "CONCRETO"}, {"cat": "S", "num": null, "par": "GORILLA"}, {"cat": "P", "num": null, "par": "GABINETTO"}, {"cat": "O", "num": null, "par": "PIEDISTALLO"}, {"cat": "A", "num": 1, "par": "SCOMPARIRE"}, {"cat": "?", "num": 1, "par": "MORTIFICATO"}, {"cat": "S", "num": null, "par": "PAVIMENTAZIONE"}, {"cat": "P", "num": 1, "par": "GUARDAROBA"}, {"cat": "O", "num": null, "par": "LAMPEGGIATORE"}, {"cat": "A", "num": null, "par": "EVITARE"}, {"cat": "?", "num": 1, "par": "STRETTO"}, {"cat": "S", "num": null, "par": "BABBO NATALE"}, {"cat": "P", "num": 1, "par": "CAVIGLIA"}, {"cat": "O", "num": 1, "par": "UOVO"}, {"cat": "A", "num": null, "par": "VEDERE"}, {"cat": "?", "num": null, "par": "INCENDIO DOLOSO"}, {"cat": "S", "num": null, "par": "SENSO UNICO"}, {"cat": "P", "num": 0, "par": "NONNO"}, {"cat": "O", "num": 1, "par": "CUCCHIAINO"}, {"cat": "A", "num": 0, "par": "SPECULARE"}, {"cat": "?", "num": 1, "par": "FILA INDIANA"}, {"cat": "S", "num": 0, "par": "FUOCO"}, {"cat": "P", "num": 1, "par": "SOTTOSUOLO"}, {"cat": "O", "num": null, "par": "GIARRETTIERA"}, {"cat": "A", "num": 1, "par": "IMBACUCCARE"}, {"cat": "?", "num": null, "par": "BOSCAIOLO"}, {"cat": "S", "num": null, "par": "CIECO"}, {"cat": "P", "num": 1, "par": "BOCCA"}, {"cat": "O", "num": null, "par": "PASSERELLA"}, {"cat": "A", "num": null, "par": "INARCARE"}, {"cat": "?", "num": 1, "par": "CALMO"}, {"cat": "S", "num": null, "par": "MARKETING"}, {"cat": "P", "num": null, "par": "RISTORANTE"}, {"cat": "O", "num": 1, "par": "CUBETTO DI GHIACCIO"}, {"cat": "A", "num": 1, "par": "SONNECCHIARE"}, {"cat": "?", "num": null, "par": "POKER"}, {"cat": "S", "num": null, "par": "IMBUTO"}, {"cat": "P", "num": null, "par": "CAPELLI"}, {"cat": "O", "num": null, "par": "SEGA"}, {"cat": "A", "num": 1, "par": "RINVIARE"}, {"cat": "?", "num": 1, "par": "DIAPASON"}, {"cat": "S", "num": null, "par": "STELLA CADENTE"}, {"cat": "P", "num": null, "par": "EST"}, {"cat": "O", "num": null, "par": "FUCILE"}, {"cat": "A", "num": 1, "par": "SALDARE"}, {"cat": "?", "num": 1, "par": 
  "SUCCO"}, {"cat": "S", "num": null, "par": "MORBILLO"}, {"cat": "P", "num": null, "par": "SANBERNARDO"}, {"cat": "O", "num": null, "par": "SCUDO"}, {"cat": "A", "num": 1, "par": "FARE"}, {"cat": "?", "num": 1, "par": "POEMA"}, {"cat": "S", "num": null, "par": "TINTINNARE"}, {"cat": "P", "num": null, "par": "PANDA"}, 
  {"cat": "O", "num": 1, "par": "OCCHIALI DA SOLE"}, {"cat": "A", "num": 1, "par": "ASCIUGARE"}, {"cat": "?", "num": null, "par": "SVANTAGGIO"}, {"cat": "S", "num": null, "par": "REMO"}, {"cat": "P", "num": 1, "par": "CASA GALLEGGIANTE"}, {"cat": "O", "num": null, "par": "SASSOFONO"}, {"cat": "A", "num": null, "par": "INGIURIARE"}, {"cat": "?", "num": 1, "par": "PARAGRAFO"}, {"cat": "S", "num": null, "par": "CARRO ARMATO"}, {"cat": "P", "num": null, "par": "CAPRA"}, {"cat": 
  "O", "num": null, "par": "RAGGI DELLA RUOTA"}, {"cat": "A", "num": 1, "par": "BAGNARE"}, {"cat": "?", "num": 1, "par": "TAPPI PER LE ORECCHIE"}, {"cat": "S", "num": null, "par": "DRAGO"}, {"cat": "P", "num": null, "par": "SIGNORA"}, {"cat": "O", "num": 1, "par": "VIOLINO"}, {"cat": "A", "num": 1, "par": "INVADERE"}, 
  {"cat": "?", "num": null, "par": "GRUPPO"}, {"cat": "S", "num": null, "par": "NONNA"}, {"cat": "P", "num": null, "par": "CHIRURGO"}, {"cat": "O", "num": 1, "par": "INSEGNA"}, {"cat": "A", "num": null, "par": "PICCHETTARE"}, {"cat": "?", "num": 1, "par": "GERMOGLIO"}, {"cat": "S", "num": null, "par": "SPACCATA"}, {"cat": "P", "num": null, "par": "CAVALLO"}, {"cat": "O", "num": null, "par": "CALZA"}, {"cat": "A", "num": 1, "par": "SCALPELLARE"}, {"cat": "?", "num": 1, "par": "INFLAZIONE"}, {"cat": "S", "num": null, "par": "OMBRA"}, {"cat": "P", "num": null, "par": "DENTE"}, {"cat": "O", "num": 1, "par": "FIONDA"}, {"cat": "A", "num": null, "par": "VARARE"}, {"cat": "?", "num": 1, "par": "SPATOLA"}, {"cat": "S", "num": null, "par": "CORTEO"}, {"cat": "P", "num": null, "par": "PIANO INFERIORE"}, {"cat": "O", "num": null, "par": "PIEDE DI PORCO"}, {"cat": "A", "num": 1, "par": "FRATTURARE"}, {"cat": "?", "num": 1, "par": "MEDIA"}, {"cat": "S", "num": null, "par": "PAPILLON"}, {"cat": "P", "num": 1, "par": "TOKYO"}, {"cat": "O", "num": null, "par": "GRATTUGGIA PER FORMAGGIO"}, {"cat": "A", "num": 1, "par": "RADERE AL SUOLO"}, {"cat": "?", "num": null, "par": "TEST"}, {"cat": "S", "num": null, "par": "PICTIONARY"}, {"cat": "P", "num": null, "par": "AFRICA"}, 
  {"cat": "O", "num": null, "par": "SPECCHIO"}, {"cat": "A", "num": 1, "par": "TOCCARE"}, {"cat": "?", "num": 1, "par": "SOPRA"}, {"cat": "S", "num": null, "par": "ALGA"}, {"cat": "P", "num": 1, "par": "PARASSITA"}, {"cat": "O", "num": null, "par": "CASSETTA DEGLI ATTREZZI"}, {"cat": "A", "num": null, "par": "ALTERNARE"}, {"cat": "?", "num": 1, "par": "TIZZONE"}, {"cat": "S", "num": null, "par": "PREMIO"}, {"cat": "P", "num": 1, "par": "SALA DA GIOCO"}, {"cat": "O", "num": 1, "par": "STIVALI"}, {"cat": "A", "num": 0, "par": "RUZZOLARE"}, {"cat": "?", "num": 0, "par": "BRETELLA"}, {"cat": "S", "num": 0, "par": "SCIARADA"}, {"cat": 
  "P", "num": null, "par": "CESTA DEL CANE"}, {"cat": "O", "num": null, "par": "SPORTELLO"}, {"cat": "A", "num": 1, "par": "STRAPPARE"}, {"cat": "?", "num": 1, "par": "FIASCO"}, {"cat": "S", "num": null, "par": "CIRCONDARE"}, {"cat": "P", "num": 1, "par": "CIVETTA"}, {"cat": "O", "num": null, "par": "TRATTORE"}, {"cat": "A", "num": 1, "par": "RICALCARE"}, {"cat": "?", "num": null, "par": "BESSELLER"}, {"cat": "S", "num": null, "par": "POZZANGHERA"}, {"cat": "P", "num": null, "par": "PIOVRA"}, {"cat": "O", "num": 1, "par": "PETALO"}, {"cat": "A", "num": 1, "par": "SENTIRE"}, {"cat": "?", "num": null, "par": "PORO"}, {"cat": "S", "num": null, "par": "FONDUTA"}, {"cat": "P", "num": 1, "par": "VIALE"}, {"cat": "O", "num": 1, "par": "MOBILE"}, {"cat": "A", "num": null, "par": "ESAMINARE"}, {"cat": "?", "num": null, "par": "RICHIAMO DELLA FORESTA"}, {"cat": "S", "num": null, "par": "DONNA"}, {"cat": "P", "num": 1, "par": "TASSO"}, {"cat": "O", "num": null, "par": "FOCACCINA"}, {"cat": "A", "num": null, "par": "COPIARE"}, {"cat": "?", "num": 1, "par": "SEDIA ELETTRICA"}, {"cat": "S", "num": null, "par": "TIMIDO"}, {"cat": "P", "num": 1, "par": "CALAMARO"}, {"cat": "O", "num": null, "par": "RAGGIO LASER"}, {"cat": "A", "num": null, "par": "DISERBARE"}, {"cat": "?", "num": 1, "par": "MOLTIPLICARE"}, {"cat": "S", "num": null, "par": "WINDSURF"}, {"cat": "P", "num": 1, "par": "BRACCIDFERRO"}, {"cat": "O", "num": null, "par": "STRINGA"}, {"cat": "A", "num": 1, "par": "ADATTARE"}, {"cat": "?", "num": null, "par": "GIOVEDI'"}, {"cat": "S", "num": null, "par": "TAGLIO DI CAPELLI"}, {"cat": "P", "num": 1, "par": "CRANIO"}, {"cat": "O", "num": null, "par": "OBIETTIVO"}, {"cat": "A", "num": 1, "par": "ARCHIVIARE"}, {"cat": "?", "num": null, "par": "PRESCRIZIONE"}, {"cat": "S", "num": null, "par": "RUOTA DEL CARRO"}, {"cat": "P", "num": null, "par": "ROMA"}, {"cat": "O", "num": 1, "par": "SEDIA"}, {"cat": "A", "num": 1, "par": "FERMARE"}, {"cat": "?", "num": null, "par": "BIBITA ANALCOLICA"}, {"cat": "S", "num": null, "par": "NUVOLOSO"}, {"cat": "P", "num": 1, "par": "PIANURA PADANA"}, {"cat": "O", "num": 1, "par": "DOLLARO"}, {"cat": "A", "num": null, "par": "SGOCCIOLARE"}, {"cat": "?", "num": null, "par": 
  "ASSAGGIO"}, {"cat": "S", "num": null, "par": "POSITIVO"}, {"cat": "P", "num": 1, "par": "SQUALO"}, {"cat": "O", "num": null, "par": "PALLOTTOLIERE"}, {"cat": 
  "A", "num": null, "par": "BUTTARE"}, {"cat": "?", "num": 1, "par": "CALDAIA"}, {"cat": "S", "num": null, "par": "SOTTOMARINO"}, {"cat": "P", "num": 1, "par": "GEMELLI SIAMESI"}, {"cat": "O", "num": null, "par": "RISMA"}, {"cat": "A", "num": 1, "par": "NUMERARE"}, {"cat": "?", "num": null, "par": "MARTEDI' GRASSO"}, {"cat": "S", "num": null, "par": "BRIDGE"}, {"cat": "P", "num": 1, "par": "RANCH"}, {"cat": "O", "num": 1, "par": "RISVOLTO DELLA GIACCA"}, {"cat": "A", "num": 
  null, "par": "ARRICCIARE"}, {"cat": "?", "num": null, "par": "STRANIERO"}, {"cat": "S", "num": null, "par": "FERMAPORTA"}, {"cat": "P", "num": 1, "par": "STAZIONE SPAZIALE"}, {"cat": "O", "num": null, "par": "MONOROTALA"}, {"cat": "A", "num": null, "par": "INTAGLIARE"}, {"cat": "?", "num": 1, "par": "CUCITRICE"}, {"cat": "S", "num": null, "par": "PI\u00d1COLADA"}, {"cat": "P", "num": null, "par": "MEDIO ORIENTE"}, {"cat": "O", "num": 1, "par": "PETARDO"}, {"cat": "A", "num": null, "par": "VIAGGIARE"}, {"cat": "?", "num": 1, "par": "SALUTE"}, {"cat": "S", "num": null, "par": "MANDRAKE"}, {"cat": "P", "num": 1, "par": "PAESE"}, {"cat": "O", "num": 1, "par": "HAMBURGER"}, {"cat": "A", "num": null, "par": "INGHIOTTIRE"}, {"cat": "?", "num": null, "par": "VALLE DELLA MORTE"}, {"cat": "S", 
  "num": null, "par": "LARINGITE"}, {"cat": "P", "num": 1, "par": "PLUTONE"}, {"cat": "O", "num": null, "par": "RUBINETTO"}, {"cat": "A", "num": 1, "par": "DIRIGERE"}, {"cat": "?", "num": null, "par": "IMPORTAZIONE"}, {"cat": "S", "num": null, "par": "CAMINETTO"}, {"cat": "P", "num": 1, "par": "ORNITORINCO"}, {"cat": "O", "num": 0, "par": "MONOCICLO"}, {"cat": "A", "num": 1, "par": "CUCINARE"}, {"cat": "?", "num": 0, "par": "MULA"}, {"cat": "S", "num": 0, "par": "POLO"}, {"cat": "P", "num": 1, "par": "CAPOBANDA"}, {"cat": "O", "num": 1, "par": "ARCA DI NOE'"}, {"cat": "A", "num": 0, "par": "SPIARE"}, {"cat": "?", "num": 0, "par": 
  "MUSICA"}, {"cat": "S", "num": 0, "par": "POVERO"}, {"cat": "P", "num": null, "par": "INGHILTERRA"}, {"cat": "O", "num": 1, "par": "MELA"}, {"cat": "A", "num": null, "par": "INALARE"}, {"cat": "?", "num": 1, "par": "PASSATO"}, {"cat": "S", "num": null, "par": "CORPETTO"}, {"cat": "P", "num": null, "par": "MICIO"}, {"cat": "O", "num": 1, "par": "BILANCERE"}, {"cat": "A", "num": 1, "par": "AGITARSI"}, {"cat": "?", "num": null, "par": "RIPARATORE"}, {"cat": "S", "num": null, 
  "par": "OCCHIO DI BUE"}, {"cat": "P", "num": null, "par": "CANE SELVATICO"}, {"cat": "O", "num": 1, "par": "MATTONE"}, {"cat": "A", "num": 1, "par": "RINGHIARE"}, {"cat": "?", "num": null, "par": "TESTA D'ALCE"}, {"cat": "S", "num": null, "par": "CONCHIGLIA"}, {"cat": "P", "num": 1, "par": "STAZIONE DEGLI AUTOBUS"}, 
  {"cat": "O", "num": null, "par": "STATUA"}, {"cat": "A", "num": 1, "par": "SOGNARE"}, {"cat": "?", "num": null, "par": "CONVESSO"}, {"cat": "S", "num": null, "par": "STRUMENTO"}, {"cat": "P", "num": null, "par": "QUADRUPEDE"}, {"cat": "O", "num": null, "par": "BUSTA"}, {"cat": "A", "num": 1, "par": "SURRISCALDARE"}, 
  {"cat": "?", "num": 1, "par": "QUATTROCCHI"}, {"cat": "S", "num": null, "par": "COMA"}, {"cat": "P", "num": 1, "par": "PSICHIATRA"}, {"cat": "O", "num": null, 
  "par": "SOMBRERO"}, {"cat": "A", "num": 1, "par": "STAMPARE"}, {"cat": "?", "num": null, "par": "CARTA"}, {"cat": "S", "num": null, "par": "PUNTURA"}, {"cat": 
  "P", "num": null, "par": "GUFO REALE"}, {"cat": "O", "num": 1, "par": "PERISCOPIO"}, {"cat": "A", "num": 1, "par": "VOTARE"}, {"cat": "?", "num": null, "par": 
  "INDICAZIONE"}, {"cat": "S", "num": null, "par": "PORCOSPINO"}, {"cat": "P", "num": 1, "par": "CLAUDIO BAGLIONI"}, {"cat": "O", "num": null, "par": "PASTINA"}, {"cat": "A", "num": 1, "par": "IMBRATTARE"}, {"cat": "?", "num": null, "par": "FOCHERELLO"}, {"cat": "S", "num": null, "par": "NORDEST"}, {"cat": "P", "num": 
  1, "par": "GERUSALEMME"}, {"cat": "O", "num": 1, "par": "METEORA"}, {"cat": "A", "num": null, "par": "RALLEGRARE"}, {"cat": "?", "num": null, "par": "SQUADRA"}, {"cat": "S", "num": null, "par": "CINTURA NERA"}, {"cat": "P", "num": 1, "par": "CAVALIERE"}, {"cat": "O", "num": 1, "par": "URNA"}, {"cat": "A", "num": null, "par": "FORGIARE"}, {"cat": "?", "num": null, "par": "LATERALMENTE"}, {"cat": "S", "num": null, "par": "CORSA DI SLITTE"}, {"cat": "P", "num": 1, "par": "CATTEDRALE"}, {"cat": "O", "num": null, "par": "CORAZZA"}, {"cat": "A", "num": null, "par": "DEDICARE"}, {"cat": "?", "num": 1, "par": "TONNELLATA"}, {"cat": "S", "num": null, "par": "OVALE"}, {"cat": "P", "num": null, "par": "CILE"}, {"cat": "O", "num": 1, "par": "BAMBOLA"}, {"cat": "A", "num": null, "par": "SPANDERE"}, {"cat": "?", "num": 1, "par": "PALCOSCENICO"}, {"cat": "S", "num": null, "par": "CANZONE"}, {"cat": "P", "num": null, "par": "GIUSEPPE GARIBALDI"}, {"cat": "O", "num": 1, "par": "TUTU'"}, {"cat": "A", "num": 1, "par": "CHIUDERE A CHIAVE"}, {"cat": "?", "num": null, "par": "SALSA"}, {"cat": "S", "num": null, "par": 
  "GIRADISCHI"}, {"cat": "P", "num": 1, "par": "BALENA"}, {"cat": "O", "num": 1, "par": "CINTURA"}, {"cat": "A", "num": null, "par": "APPASSIRE"}, {"cat": "?", "num": null, "par": "PRANZO"}, {"cat": "S", "num": null, "par": "TERMOMETRO"}, {"cat": "P", "num": 1, "par": "SCUOLA"}, {"cat": "O", "num": null, "par": "FORNO"}, {"cat": "A", "num": 1, "par": "SLOGARSI"}, {"cat": "?", "num": null, "par": "COMMOZIONCEREBRALE"}, {"cat": "S", "num": null, "par": "FANTASMA"}, {"cat": "P", "num": 1, "par": "CASSIUS CLAY"}, {"cat": "O", "num": 1, "par": "ELMO"}, {"cat": "A", "num": 1, "par": "STREGARE"}, {"cat": "?", "num": null, "par": "\u03a4\u039f\u039d\u039f"}, {"cat": "S", "num": null, "par": "VIRGOLETTE"}, {"cat": "P", "num": 0, "par": "VILLAGGIO"}, {"cat": "O", "num": 1, "par": "FERITOIA"}, {"cat": "A", "num": 1, "par": "GIRARE UN FILM"}, {"cat": "?", "num": 0, "par": "ACQUA BOLLENTE"}, {"cat": "S", "num": 0, "par": "PULCE"}, {"cat": "P", "num": null, "par": "MOLARE"}, {"cat": "O", "num": 1, "par": "SVEGLIA"}, {"cat": "A", "num": 1, "par": "VERSARE"}, {"cat": "?", "num": null, "par": "POLPETTA"}, {"cat": "S", "num": null, "par": "BICCHIERE DI VINO"}, {"cat": "P", "num": null, "par": "TOPO"}, {"cat": "O", "num": null, "par": "BIGLIETTO"}, {"cat": "A", "num": 1, "par": "ERUTTARE"}, {"cat": "?", "num": 1, "par": "PRIMA GUERRA MONDIALE"}, {"cat": "S", "num": null, "par": "VISIERA"}, {"cat": "P", "num": null, "par": "AMAZZONE"}, {"cat": "O", "num": null, "par": "SCIARPA"}, {"cat": "A", "num": 1, "par": "AVVELENARE"}, {"cat": "?", "num": 1, "par": "PAROLA"}, {"cat": "S", "num": null, "par": "PARCHIMETRO"}, {"cat": "P", "num": null, "par": "TORRE"}, {"cat": "O", "num": null, "par": "PALLINA DA CRICKET"}, {"cat": "A", "num": 1, "par": "CHIEDERE"}, {"cat": "?", "num": 1, "par": "VENTOSO"}, {"cat": "S", "num": null, "par": "TITANIC"}, {"cat": "P", "num": 1, "par": "SATURNO"}, {"cat": "O", "num": null, "par": "SALTINMENTE"}, {"cat": "A", "num": null, "par": "PRENDERE"}, {"cat": "?", "num": 1, "par": "TITAP"}, {"cat": "S", "num": null, "par": "CORROSIONE"}, {"cat": "P", "num": 1, "par": "UNIVERSITA'"}, {"cat": "O", "num": null, "par": "COLLANA"}, {"cat": "A", "num": 1, "par": "COGLIERE"}, {"cat": "?", "num": 
  null, "par": "ZOPPO"}, {"cat": "S", "num": null, "par": "NUVOLA"}, {"cat": "P", "num": 1, "par": "AL PACINO"}, {"cat": "O", "num": 1, "par": "RAGGI X"}, {"cat": "A", "num": null, "par": "DIVORZIARE"}, {"cat": "?", "num": null, "par": "CHIOSCO"}, {"cat": "S", "num": null, "par": "NASTRO ADESIVO"}, {"cat": "P", "num": 
  1, "par": "SUD"}, {"cat": "O", "num": null, "par": "FRIGORIFERO"}, {"cat": "A", "num": null, "par": "GRACCHIARE"}, {"cat": "?", "num": 1, "par": "BUNKER"}, {"cat": "S", "num": null, "par": "IDROREPELLENTE"}, {"cat": "P", "num": 1, "par": "ORFANO"}, {"cat": "O", "num": null, "par": "PRESERVATIVO"}, {"cat": "A", "num": 1, "par": "DECAPITARE"}, {"cat": "?", "num": null, "par": "VENERDI'"}, {"cat": "S", "num": null, "par": "PONTE LEVATOIO"}, {"cat": "P", "num": 1, "par": "RIVIERA"}, {"cat": "O", "num": null, "par": "RULLO TRASPORTATORE"}, {"cat": "A", "num": 1, "par": "SURGELARE"}, {"cat": "?", "num": null, "par": "CONVERSAZIONE"}, 
  {"cat": "S", "num": null, "par": "RECINTO"}, {"cat": "P", "num": null, "par": "FORESTA NERA"}, {"cat": "O", "num": 1, "par": "VETRO"}, {"cat": "A", "num": 1, "par": "RICORDARE"}, {"cat": "?", "num": null, "par": "GIOIELLO"}, {"cat": "S", "num": null, "par": "RAGGIO"}, {"cat": "P", "num": null, "par": "RONALD REAGAN"}, {"cat": "O", "num": 1, "par": "CANDELABRO"}, {"cat": "A", "num": 1, "par": "INVENTARE"}, {"cat": "?", "num": null, "par": "BRIOCHE"}, {"cat": "S", "num": null, "par": "MARTE"}, {"cat": "P", "num": null, "par": "TIGRE"}, {"cat": "O", "num": 1, "par": "TRECCIA"}, {"cat": "A", "num": 1, "par": "DUELLARE"}, {"cat": "?", "num": null, "par": "PASSEPARTOUT"}, {"cat": "S", "num": null, "par": "SCARPONI"}, {"cat": "P", "num": null, "par": "ITALIA"}, {"cat": "O", "num": 1, "par": 
  "PIANTA"}, {"cat": "A", "num": null, "par": "MACIULLARE"}, {"cat": "?", "num": 1, "par": "BIBBIA"}, {"cat": "S", "num": null, "par": "DESERTO DEL SAHARA"}, {"cat": "P", "num": null, "par": "SARDO"}, {"cat": "O", "num": 1, "par": "CERNIERA LAMPO"}, {"cat": "A", "num": 1, "par": "SBUFFARE"}, {"cat": "?", "num": null, "par": "PANIFICIO"}, {"cat": "S", "num": null, "par": "PASSO CARRABILE"}, {"cat": "P", "num": 1, "par": "VESPA"}, {"cat": "O", "num": null, "par": "FORMAGGIO SVIZZERO"}, {"cat": "A", "num": 1, "par": "DOLCIFICARE"}, {"cat": "?", "num": null, "par": "APPLICAZIONE"}, {"cat": "S", "num": null, "par": "GUIDA"}, {"cat": "P", "num": null, "par": "GIRINO"}, {"cat": "O", "num": 1, "par": "TRAPPOLA PER TOPI"}, {"cat": "A", "num": null, "par": "COMPLETARE"}, {"cat": "?", "num": 1, "par": "VANITOSO"}, {"cat": "S", "num": null, "par": "NOVE"}, {"cat": "P", "num": 1, "par": "PESCE GATTO"}, {"cat": "O", "num": 0, "par": "STECCATO"}, {"cat": "A", "num": 0, "par": "AVVICINARE"}, {"cat": "?", "num": 1, "par": "PAROLA D'ORDINE"}, {"cat": "S", "num": 0, "par": "STAMPELLA"}, {"cat": "P", "num": 1, "par": 
  "UFFICIO"}, {"cat": "O", "num": 1, "par": "ORECCHINO CON DIAMANTE"}, {"cat": "A", "num": null, "par": "ANSIMARE"}, {"cat": "?", "num": null, "par": "ENORME"}, 
  {"cat": "S", "num": null, "par": "JUVENTUS"}, {"cat": "P", "num": null, "par": "LOANGELES"}, {"cat": "O", "num": 1, "par": "PARRUCCHINO"}, {"cat": "A", "num": 
  null, "par": "SRADICARE"}, {"cat": "?", "num": 1, "par": "CAPSULA"}, {"cat": "S", "num": null, "par": "MARADONA"}, {"cat": "P", "num": null, "par": "MILLEPIEDI"}, {"cat": "O", "num": 1, "par": "PARAORECCHIE"}, {"cat": "A", "num": 1, "par": "AMPUTARE"}, {"cat": "?", "num": null, "par": "REPORTER"}, {"cat": "S", "num": null, "par": "MARMITTA"}, {"cat": "P", "num": null, "par": "UNGHIA DEL PIEDE"}, {"cat": "O", "num": 1, "par": "TORCIA ELETTRICA"}, {"cat": "A", "num": 1, "par": "IRRIGARE"}, {"cat": "?", "num": null, "par": "COLLO DI BOTTIGLIA"}, {"cat": "S", "num": null, "par": "CAPO"}, {"cat": "P", "num": 1, "par": "GLADIATORE"}, 
  {"cat": "O", "num": null, "par": "BULLDOZER"}, {"cat": "A", "num": 1, "par": "IMBROGLIARE"}, {"cat": "?", "num": null, "par": "FONDATO"}, {"cat": "S", "num": null, "par": "IDEA"}, {"cat": "P", "num": null, "par": "RUSSIA"}, {"cat": "O", "num": 1, "par": "BENDA PER OCCHI"}, {"cat": "A", "num": 1, "par": "SFONDARE"}, {"cat": "?", "num": null, "par": "CUORE SPEZZATO"}, {"cat": "S", "num": null, "par": "SLOT MACHINE"}, {"cat": "P", "num": null, "par": "POLO NORD"}, {"cat": "O", "num": null, "par": "MARSUPIO"}, {"cat": "A", "num": 1, "par": "ABBRONZARSI"}, {"cat": "?", "num": 1, "par": "ESERCIZIO"}, {"cat": "S", "num": null, "par": "CARDINE"}, {"cat": "P", "num": 1, "par": "TAVERNA"}, {"cat": "O", "num": 1, "par": "SEGGIOLONE"}, {"cat": "A", "num": null, "par": "DIPLOMARSI"}, {"cat": "?", 
  "num": null, "par": "DEPLIANT"}, {"cat": "S", "num": null, "par": "ARCOBALENO"}, {"cat": "P", "num": 1, "par": "GIOCONDA"}, {"cat": "O", "num": null, "par": "TAVOLA DA SURF"}, {"cat": "A", "num": 1, "par": "TESTARE"}, {"cat": "?", "num": null, "par": "CANDELA DEL MOTORE"}, {"cat": "S", "num": null, "par": "DENARO"}, 
  {"cat": "P", "num": null, "par": "CIGNO"}, {"cat": "O", "num": null, "par": "ARATRO"}, {"cat": "A", "num": 1, "par": "SALTARE"}, {"cat": "?", "num": 1, "par": 
  "AHIA!"}, {"cat": "S", "num": null, "par": "ANIMALE"}, {"cat": "P", "num": 1, "par": "PELLEGRINO"}, {"cat": "O", "num": null, "par": "CARTA MOSCHICIDA"}, {"cat": "A", "num": null, "par": "CAMMINARE SULL'ACQUA"}, {"cat": "?", "num": 1, "par": "ECLISSI"}, {"cat": "S", "num": null, "par": "BACHETTE CINESI"}, {"cat": "P", "num": null, "par": "SORELLA"}, {"cat": "O", "num": 1, "par": "IGLOO"}, {"cat": "A", "num": 1, "par": "SIMULARE"}, {"cat": "?", "num": null, "par": "ELASTICO"}, {"cat": "S", "num": null, "par": "TRENO MERCI"}, {"cat": "P", "num": 1, "par": "MOSCHEA"}, {"cat": "O", "num": null, "par": "TATUAGGIO"}, {"cat": "A", "num": null, "par": "ERIGERE"}, {"cat": "?", "num": 1, "par": "SEPARAZIONE"}, {"cat": "S", "num": null, "par": "GHIACCIAIO"}, {"cat": "P", "num": 1, "par": "RIGA DEI CAPELLI"}, {"cat": "O", "num": null, "par": "SPAVENTAPASSERI"}, {"cat": "A", "num": null, "par": "SROTOLARE"}, {"cat": "?", "num": 1, "par": "BRACCIO ROTTO"}, {"cat": "S", "num": null, "par": "ODORE"}, {"cat": "P", "num": null, "par": "PENSIONE"}, {"cat": "O", "num": null, "par": "STUOIA"}, {"cat": "A", "num": 1, 
  "par": "ACCOVACCIARSI"}, {"cat": "?", "num": 1, "par": "USCITA DI SICUREZZA"}, {"cat": "S", "num": null, "par": "PARADISO"}, {"cat": "P", "num": 1, "par": "GEMELLO"}, {"cat": "O", "num": null, "par": "UN QUARTO"}, {"cat": "A", "num": null, "par": "DISCORRERE"}, {"cat": "?", "num": 1, "par": "STRETTOIA"}, {"cat": "S", "num": null, "par": "VENTO"}, {"cat": "P", "num": 1, "par": "TACCHINO"}, {"cat": "O", "num": null, "par": "TELEFONO"}, {"cat": "A", "num": 1, "par": "DORMIRE"}, {"cat": "?", "num": null, "par": "MINUTO"}, {"cat": "S", "num": null, "par": "PROFILO"}, {"cat": "P", "num": 0, "par": "CRISTOFORO COLOMBO"}, {"cat": "O", "num": 1, "par": "MAZZA DA GOLF"}, {"cat": "A", "num": 1, "par": "SPAZZARE"}, {"cat": "?", "num": 0, "par": "SBROGLIARE"}, {"cat": "S", "num": 0, "par": "PRATO"}, {"cat": "P", "num": 1, "par": "MONDO"}, {"cat": "O", "num": null, "par": "SCHIUMA DA BARBA"}, {"cat": "A", "num": null, "par": "MISURARE"}, {"cat": "?", "num": 1, "par": "SONNAMBULISMO"}, {"cat": "S", "num": null, "par": "GAMBE ACCAVALLATE"}, {"cat": "P", "num": null, "par": "FRANCIA"}, {"cat": "O", "num": null, "par": "MATITA"}, {"cat": "A", "num": 1, "par": "GALOPPARE"}, {"cat": "?", "num": null, "par": "RUOTA PANORAMICA"}, {"cat": "S", "num": null, "par": "CORSA IPPICA"}, {"cat": "P", "num": null, "par": "CAPANNONE"}, {"cat": "O", "num": 1, "par": "UFO"}, {"cat": "A", "num": 1, "par": "ATTERRARE"}, {"cat": "?", "num": null, "par": "SGUARDO"}, {"cat": "S", "num": null, "par": "MULINO A VENTO"}, {"cat": "P", "num": 1, "par": "MAGGIORDOMO"}, {"cat": "O", "num": 1, "par": "CERCHIO"}, {"cat": "A", "num": null, "par": "COMPRARE"}, {"cat": "?", "num": null, "par": "TUBAZIONE"}, {"cat": "S", "num": null, "par": "BOMBA DI PROFONDITA'"}, {"cat": "P", "num": 1, "par": "ALBERTO SORDI"}, {"cat": "O", "num": 1, "par": "MAGLIETTA"}, {"cat": "A", "num": null, "par": "ODORARE"}, {"cat": "?", "num": null, "par": "UOVO CON BACON"}, {"cat": "S", "num": null, "par": "FORCHETTA"}, {"cat": "P", "num": null, "par": "AREA DI RIGORE"}, {"cat": "O", "num": 1, "par": "LUCCHETTO"}, {"cat": "A", "num": null, "par": "SPOLVERARE"}, {"cat": "?", "num": 1, "par": "DIARIO"}, {"cat": "S", "num": null, "par": "VELOCITA' DI ATTERRAGGIO"}, 
  {"cat": "P", "num": 1, "par": "CLEOPATRA"}, {"cat": "O", "num": null, "par": "OMBRELLO"}, {"cat": "A", "num": 1, "par": "LEGARE"}, {"cat": "?", "num": null, "par": "MINUSCOLO"}, {"cat": "S", "num": null, "par": "PORTA GIREVOLE"}, {"cat": "P", "num": null, "par": "CIMICE"}, {"cat": "O", "num": 1, "par": "REGISTRATORE"}, {"cat": "A", "num": 1, "par": "FONDERE"}, {"cat": "?", "num": null, "par": "PALLANUOTO"}, {"cat": "S", "num": null, "par": "REGGISENO"}, {"cat": "P", "num": 1, "par": "BOLOGNA"}, {"cat": "O", "num": null, "par": "SACCO DI SABBIA"}, {"cat": "A", "num": 1, "par": "TORMENTARE"}, {"cat": "?", "num": null, "par": "TRAZIONE"}, {"cat": "S", "num": null, "par": "PINZETTE"}, {"cat": "P", "num": null, "par": "FORMICA"}, {"cat": "O", "num": 1, "par": "ZUCCA"}, {"cat": "A", "num": 
  1, "par": "RASCHIARE"}, {"cat": "?", "num": null, "par": "DISPENSA"}, {"cat": "S", "num": null, "par": "ORSA MAGGIORE"}, {"cat": "P", "num": 1, "par": "VELODROMO"}, {"cat": "O", "num": null, "par": "BRACCIALETTO"}, {"cat": "A", "num": 1, "par": "INCHINARSI"}, {"cat": "?", "num": null, "par": "PING PONG"}, {"cat": "S", "num": null, "par": "MURO"}, {"cat": "P", "num": null, "par": "CAMMELLO"}, {"cat": "O", "num": null, "par": "LANCIA"}, {"cat": "A", "num": 1, "par": "SCARROZZARE"}, {"cat": "?", "num": 1, "par": "SALA OPERATORIA"}, {"cat": "S", "num": null, "par": "SINA"}, {"cat": "P", "num": 1, "par": "CASTORO"}, {"cat": "O", "num": null, "par": "CANDELA"}, {"cat": "A", "num": 1, "par": "CAPOVOLGERSI"}, {"cat": "?", "num": 1, "par": "BECCHIME"}, {"cat": "S", "num": null, "par": "FORFORA"}, {"cat": "P", "num": null, "par": "IPPOPOTAMO"}, {"cat": "O", "num": 1, "par": "FOSSILE"}, {"cat": "A", "num": null, "par": "AFFIBBIARE"}, {"cat": "?", "num": 1, "par": "PORTARE AVANTI"}, {"cat": "S", "num": null, "par": "RIPIDO"}, {"cat": "P", "num": 1, "par": "INCISIVO"}, {"cat": "O", "num": null, "par": "MONOPOLI"}, {"cat": "A", "num": 1, "par": "DIMENTICARE"}, {"cat": "?", "num": null, "par": "BOTTIGLIA DI BIRRA"}, {"cat": "S", "num": null, "par": "TEMPESTA DI NEVE"}, {"cat": "P", "num": null, "par": "PELLICANO"}, {"cat": "O", "num": null, "par": "POMPON"}, {"cat": "A", "num": 1, "par": "DOPPIARE"}, {"cat": "?", "num": 1, "par": "MAGRO"}, {"cat": "S", "num": null, "par": "TANGA"}, {"cat": "P", "num": null, "par": "ALPI"}, {"cat": "O", "num": 1, "par": "CITOFONO"}, {"cat": "A", 
  "num": null, "par": "PRENDERE IL SOLE"}, {"cat": "?", "num": 1, "par": "TU"}, {"cat": "S", "num": null, "par": "BASSO"}, {"cat": "P", "num": 0, "par": "PIEMONTE"}, {"cat": "O", "num": 0, "par": "BISCOTTO"}, {"cat": "A", "num": 1, "par": "STRANGOLARE"}, {"cat": "?", "num": 1, "par": "SCATOLA DI FIAMMIFERI"}, {"cat": "S", "num": 0, "par": "CUGINO"}, {"cat": "P", "num": null, "par": "CAPPELLA SISTINA"}, {"cat": "O", "num": 1, "par": "SIGARETTA"}, {"cat": "A", "num": null, "par": "FRUSTARE"}, {"cat": "?", "num": 1, "par": "INVISIBILE"}, {"cat": "S", "num": null, "par": "GEYSER"}, {"cat": "P", "num": 1, "par": "GATTO"}, {"cat": "O", 
  "num": null, "par": "MONETA DA 10 LIRE"}, {"cat": "A", "num": 1, "par": "BOCCIARE"}, {"cat": "?", "num": null, "par": "INFELICE"}, {"cat": "S", "num": null, "par": "NAVICELLA SPAZIALE"}, {"cat": "P", "num": 0, "par": "ZEBRA"}, {"cat": "O", "num": 1, "par": "FAGIOLO"}, {"cat": "A", "num": 1, "par": "SPENDERE"}, {"cat": "?", "num": 0, "par": "SIMMETRICO"}, {"cat": "S", "num": 0, "par": "MURO DEL SUONO"}, {"cat": "P", "num": 1, "par": "PEARL HARBOUR"}, {"cat": "O", "num": 0, 
  "par": "ARMADIETTO"}, {"cat": "A", "num": 1, "par": "CATAPULTARE"}, {"cat": "?", "num": 0, "par": "PUNCH"}, {"cat": "S", "num": 0, "par": "HALLOWEEN"}, {"cat": "P", "num": 0, "par": null}, {"cat": "O", "num": 0, "par": null}, {"cat": "A", "num": 0, "par": null}, {"cat": "?", "num": 0, "par": null}, {"cat": "S", "num": 0, "par": null}, {"cat": "P", "num": 0, "par": null}, {"cat": "O", "num": 0, "par": null}, {"cat": "A", "num": 0, "par": null}, {"cat": "?", "num": 0, "par": null}, {"cat": "S", "num": 0, "par": null}, {"cat": "P", "num": 0, "par": null}, {"cat": "O", "num": 0, "par": null}, {"cat": "A", "num": 0, "par": null}, {"cat": "?", "num": 0, "par": null}, {"cat": "S", "num": 0, "par": null}, {"cat": "P", "num": 0, "par": null}, {"cat": "O", "num": 0, "par": null}, {"cat": "A", "num": 0, "par": null}, {"cat": "?", "num": 0, "par": null}, {"cat": "S", "num": 0, "par": null}, {"cat": "P", "num": 0, "par": null}, {"cat": "O", "num": 0, "par": null}, {"cat": "A", "num": 0, "par": null}, {"cat": "?", "num": 0, "par": null}, {"cat": "S", "num": 0, "par": null}, {"cat": "P", "num": 0, "par": "MOTEL"}, {"cat": "O", "num": 1, "par": "BURATTINO"}, {"cat": "A", "num": 1, "par": "TIRARE"}, {"cat": "?", "num": 0, "par": "PASTICCERIA"}, {"cat": "S", "num": 0, "par": "SUPERFICIE ESTERNA"}, {"cat": "P", "num": null, "par": "PONY"}, {"cat": "O", "num": 1, "par": "SCARPA"}, {"cat": "A", "num": null, "par": "SUGGERIRE"}, 
  {"cat": "?", "num": 1, "par": "SBANDAMENTO"}, {"cat": "S", "num": null, "par": "ARIA"}, {"cat": "P", "num": null, "par": "CINTOLA"}, {"cat": "O", "num": 1, "par": "PRESEPIO"}, {"cat": "A", "num": 1, "par": "SOFFOCARE"}, {"cat": "?", "num": null, "par": "SECONDO PIANO"}, {"cat": "S", "num": null, "par": "GATTO DELLE NEVI"}, {"cat": "P", "num": 0, "par": "BIBLIOTECA"}, {"cat": "O", "num": 1, "par": "FUOCHI D'ARTIFICIO"}, {"cat": "A", "num": null, "par": "FOTOGRAFARE"}, {"cat": "?", "num": 1, "par": "MANISCALCO"}, {"cat": "S", "num": 0, "par": "AGOSTO"}, {"cat": "P", "num": 1, "par": null}, {"cat": "O", "num": 0, "par": null}, {"cat": "A", "num": 1, "par": null}, {"cat": "?", "num": 0, "par": null}, {"cat": "S", "num": 0, "par": null}, {"cat": "P", "num": 0, "par": null}, {"cat": "O", "num": 0, "par": null}, {"cat": "A", "num": 0, "par": null}, {"cat": "?", "num": 0, "par": null}, {"cat": "S", "num": 0, "par": null}, {"cat": "P", "num": 0, "par": null}, {"cat": "O", "num": 0, "par": null}, {"cat": "A", "num": 0, "par": null}, {"cat": "?", "num": 0, "par": null}, {"cat": "S", "num": 0, "par": null}, 
  {"cat": "P", "num": 0, "par": null}, {"cat": "O", "num": 0, "par": null}, {"cat": "A", "num": 0, "par": null}, {"cat": "?", "num": 0, "par": null}, {"cat": "S", "num": 0, "par": null}]

  cardList: Map<number, Card> = new Map();
  cards: Card[] = [];

  ngOnInit(): void {
    for(let i = 0; i < this.data.length; i+=5) {
      this.cards.push({
        p: new P(this.data[i].num, this.data[i].par),
        o: new O(this.data[i+1].num, this.data[i+1].par),
        a: new A(this.data[i+2].num, this.data[i+2].par),
        u: new U(this.data[i+3].num, this.data[i+3].par),
        s: new S(this.data[i+4].num, this.data[i+4].par)
      });
    }

    this.cards.forEach((category, index) =>
      this.cardList.set(index + 1, category)
    );
  }

  randomIntFromInterval(min: number, max: number): number { // min and max included 
    return Math.floor(Math.random() * (max - min + 1) + min)
  }

  drawCard(cat: string) {
    let len = this.cardList.size;
    const rndInt = this.randomIntFromInterval(1, len);

    this.cat = cat;
    this.nCard = rndInt;
    this.card = this.cardList.get(this.nCard);
  }
}
